//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoldProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public Nullable<int> id_User { get; set; }
        public string menu { get; set; }
        public Nullable<int> count_Pepople { get; set; }
        public Nullable<int> tableNumber { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
